server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cruddemo?characterEncoding=UTF8
    username: root
    password: 2001
    driver-class-name: com.mysql.cj.jdbc.Driver

  spring:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 10
          min-idle: 2
      timeout: 6000